In [1]:
import numpy as np
import pandas as pd

In [50]:
date=pd.read_csv('orders.csv')
time=pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# working with dates

In [7]:
# converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
# 1. Extract year

date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
814 2019-06-13        6438       24       8       2019
558 2019-06-26        2416       26       2       2019
622 2018-09-21        3234       25       2       2018
599 2019-06-05        2373       13      16       2019
857 2019-01-20        1811       25       6       2019

###2. Extract Month

In [10]:
date['date_month_no']=date['date'].dt.month

In [11]:
date.head(2)

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8

In [12]:
# extracting month name
date['date_month_name']=date['date'].dt.month_name()

In [14]:
# day of week
date['date_dow']=date['date'].dt.dayofweek
date.head(2)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,12,December,1
1,2018-08-15,3646,14,157,2018,8,August,2

In [24]:
# day of week - name
date['date_dow_name']=date['date'].dt.day_name()
date.head(2)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow,date_dow_name,data_is_weekend,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,1,Tuesday,0,0
1,2018-08-15,3646,14,157,2018,8,August,2,Wednesday,0,0

In [25]:
# is weekend
date['data_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

In [26]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow,date_dow_name,data_is_weekend,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,1,Tuesday,0,0
1,2018-08-15,3646,14,157,2018,8,August,2,Wednesday,0,0
2,2018-10-23,1859,25,1,2018,10,October,1,Tuesday,0,0
3,2019-08-17,7292,25,1,2019,8,August,5,Saturday,1,1
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1,1

In [30]:
# extract week
date['date_week']=date['date'].dt.isocalendar().week

In [31]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow,date_dow_name,data_is_weekend,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,1,Tuesday,0,0,50
1,2018-08-15,3646,14,157,2018,8,August,2,Wednesday,0,0,33
2,2018-10-23,1859,25,1,2018,10,October,1,Tuesday,0,0,43
3,2019-08-17,7292,25,1,2019,8,August,5,Saturday,1,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1,1,1

In [33]:
date.drop(columns=(['product_id','city_id','orders','data_is_weekend']))

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,1,Tuesday,0,50
1,2018-08-15,2018,8,August,2,Wednesday,0,33
2,2018-10-23,2018,10,October,1,Tuesday,0,43
3,2019-08-17,2019,8,August,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,Sunday,1,1
...,...,...,...,...,...,...,...,...
995,2018-10-08,2018,10,October,0,Monday,0,41
996,2018-12-06,2018,12,December,3,Thursday,0,49
997,2019-05-07,2019,5,May,1,Tuesday,0,19
998,2019-03-03,2019,3,March,6,Sunday,1,9
999,2019-10-15,2019,10,October,1,Tuesday,0,42

In [38]:
#extract quarter
date['date_quater']=date['date'].dt.quarter

In [39]:
#extrat semester
date['semester']=np.where(date['date_quater'].isin([1,2]),1,2)

# extracting time from datetimstamp

In [41]:
import datetime
today=datetime.datetime.today()

In [42]:
today

datetime.datetime(2025, 4, 27, 18, 29, 32, 656936)

In [43]:
today-date['date']

0     1965 days 18:29:32.656936
1     2447 days 18:29:32.656936
2     2378 days 18:29:32.656936
3     2080 days 18:29:32.656936
4     2303 days 18:29:32.656936
                 ...
995   2393 days 18:29:32.656936
996   2334 days 18:29:32.656936
997   2182 days 18:29:32.656936
998   2247 days 18:29:32.656936
999   2021 days 18:29:32.656936
Name: date, Length: 1000, dtype: timedelta64[ns]

In [44]:
(today-date['date']).dt.days

0      1965
1      2447
2      2378
3      2080
4      2303
       ...
995    2393
996    2334
997    2182
998    2247
999    2021
Name: date, Length: 1000, dtype: int64

In [47]:
# month passed
np.round((today-date['date'])/np.timedelta64(1,'D'),0)/30

0      65.533333
1      81.600000
2      79.300000
3      69.366667
4      76.800000
         ...
995    79.800000
996    77.833333
997    72.766667
998    74.933333
999    67.400000
Name: date, Length: 1000, dtype: float64

In [51]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [52]:
time['date']=pd.to_datetime(time['date'])

In [53]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [54]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

# extract time part

In [55]:
time['time']=time['date'].dt.time

In [56]:
today-time['date']

0     4151 days 17:39:32.656936
1     4015 days 18:49:32.656936
2     4501 days 18:08:32.656936
3     3803 days 17:58:32.656936
4     4200 days 19:18:32.656936
                 ...
995   4790 days 17:39:32.656936
996   4111 days 19:15:32.656936
997   4576 days 18:52:32.656936
998   4692 days 18:55:32.656936
999   3964 days 19:04:32.656936
Name: date, Length: 1000, dtype: timedelta64[ns]

In [59]:
#extarcting in seconds

(today-time['date'])/np.timedelta64(1,'s')

0      3.587100e+08
1      3.469638e+08
2      3.889517e+08
3      3.286439e+08
4      3.629495e+08
           ...
995    4.139196e+08
996    3.552597e+08
997    3.954344e+08
998    4.054569e+08
999    3.425583e+08
Name: date, Length: 1000, dtype: float64

In [60]:
# in minutes
(today-time['date'])/np.timedelta64(1,'m')

0      5.978500e+06
1      5.782730e+06
2      6.482529e+06
3      5.477399e+06
4      6.049159e+06
           ...
995    6.898660e+06
996    5.920996e+06
997    6.590573e+06
998    6.757616e+06
999    5.709305e+06
Name: date, Length: 1000, dtype: float64

In [61]:
# in hours
(today-time['date'])/np.timedelta64(1,'h')

0       99641.659071
1       96378.825738
2      108042.142405
3       91289.975738
4      100819.309071
           ...
995    114977.659071
996     98683.259071
997    109842.875738
998    112626.925738
999     95155.075738
Name: date, Length: 1000, dtype: float64